# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: pos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    command: ["node","src/api/servers.js"]
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:3000/api-docs/swagger.json"]
      interval: 10s
      timeout: 5s
      retries: 5

  pos-app:
    build: .
    container_name: pos-app
    restart: on-failure
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - API_URL=http://api:3000/api/v1
    working_dir: /app
    stdin_open: true
    tty: true
    command: >
      sh -c "while ! nc -z api 3000; do sleep 1; done &&
             node src/appConsole.js"

  maison-mere:
    build: .
    container_name: maison-mere
    restart: on-failure
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - API_URL=http://api:3000/api/v1
    working_dir: /app
    stdin_open: true
    tty: true
    command: >
      sh -c "while ! nc -z api 3000; do sleep 1; done &&
             node src/maisonMereConsole.js"

volumes:
  pgdata:
