version: "3.11"

services:
  db:
    image: postgres:15
    container_name: pos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pos-app:
    build: .
    container_name: pos-app
    depends_on:
      - db
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
      POSTGRES_HOST: db
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: node src/appConsole.js
    
  api:
    build: .
    container_name: pos-api
    depends_on:
      - db
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
      POSTGRES_HOST: db
    working_dir: /app
    command: node src/api/servers.js
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      
  maison-mere:
    build: .
    container_name: maison-mere
    depends_on:
      - db
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
      POSTGRES_HOST: db
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: node src/maisonMereConsole.js

volumes:
  pgdata:
