version: "3.11"

services:
  app:
    build: .                 # construit l’image à partir du Dockerfile
    image: image_lab0      # nom local de l’image (facultatif mais pratique)
    container_name: image_lab0

    # ports:                 # inutile ici – pas de serveur HTTP
    #   - "3000:3000"
    # volumes:               # exemple pour recharger le code sans rebuild
    #   - ./:/app
